name: Build libArchStatic (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y
          choco install git -y

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:/vcpkg
          C:/vcpkg/bootstrap-vcpkg.bat
          C:/vcpkg/vcpkg.exe install bzip2 zlib zstd xz openssl libarchive:x64-windows-static

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release `
              -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake `
              -DBUILD_SHARED_LIBS=OFF

      - name: Build
        run: cmake --build build --config Release -- -j

      - name: Package artifacts
        run: |
          mkdir artifacts
          copy build\libArchStatic.exe artifacts\

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libArchStatic-windows
          path: artifacts/
