name: Build libArchStatic

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            runner: ubuntu-latest
            ext: ""
          - os: macos-latest
            runner: macos-latest
            ext: ""
          - os: windows-latest
            runner: windows-latest
            ext: .exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Linux: install dependencies
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git \
            libarchive-dev zlib1g-dev libbz2-dev liblzma-dev libssl-dev libzstd-dev

      # macOS: install dependencies from Homebrew (build static)
      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install cmake git libarchive zlib bzip2 xz zstd openssl
          # Force static linking by building from source
          brew reinstall --build-from-source libarchive zlib bzip2 xz zstd openssl

      # Windows: install vcpkg static libs
      - name: Setup vcpkg (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:/vcpkg
          C:/vcpkg/bootstrap-vcpkg.bat
          C:/vcpkg/vcpkg.exe install bzip2 zlib zstd xz openssl libarchive:x64-windows-static

      # Configure CMake
      - name: Configure CMake
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake \
              -DBUILD_SHARED_LIBS=OFF
          else
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF

      # Build
      - name: Build
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cmake --build build --config Release -- -j
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            cmake --build build -- -j$(sysctl -n hw.ncpu)
          else
            cmake --build build -- -j$(nproc)

      # Package artifacts
      - name: Package artifacts
        run: |
          mkdir -p artifacts
          cp build/libArchStatic${{ matrix.ext }} artifacts/

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libArchStatic-${{ matrix.os }}
          path: artifacts/
